name = "MyFirstPackage"
uuid = "5ed7fc29-c741-4fa6-8b63-56e9cc4914fc"
authors = ["LongliZheng"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
